.TH Our_printf "30 March 2023" "version 1.0"
.SH NAME

our_printf \- a version of the printf function
.SH SYNOPSIS

#include "main.h"

int printf(const char *format, ...);

_printf("%Specifier", VAR);

_printf("TEXT");

.SH DESCRIPTION

The functions in the _printf() produce output according to a format as described below. The function _printf() write output
to stdout, the standard output stream.

The _printf() function write the output under the control of a format string that specifies how subsequent arguments (or arguments
accessed via the variable-length argument facilities of stdarg()) are converted for output.

.SH BUGS
No known bugs.

.SH AUTHOR

Luis Ayala & Xai Betancourt
